### ISSUE TITLE
"WARNING: pyprojectx 3.0.7 does not provide the extra 'locked'"

### ISSUE THREAD

**Issue by DetachHead** [pyprojectx/pyprojectx#125]
**Describe the bug**

not sure if this effects anything because pyprojectx still seems to still install successfully, but i figured i should raise this in case it causes dependencies to not be locked again (same issue as #96)

when installing pyprojectx 3.0.7, pip prints the following warning:
```
WARNING: pyprojectx 3.0.7 does not provide the extra 'locked'
```

**To Reproduce**
1. run a pyprojectx command through the `./pw` wrapper eg. `./pw uv sync`

**Expected behavior**
no warning

**Screenshots**
![image](https://github.com/user-attachments/assets/1aa68c41-7137-43dc-b9a1-ad9680d9d120)

**Desktop (please complete the following information):**
 - Python  version: 3.13
 - OS: windows 11

**Comment by houbie** [comment]
fixed in 3.0.9
version 3.0.7 is yanked, so best to upgrade to the latest release
