### ISSUE TITLE
On Windows pxg wrapper script fails due to incorrect syntax

### ISSUE THREAD

**Issue by Darsstar** [pyprojectx/pyprojectx#13]
**Describe the bug**
running `pxg -i` after `px --init global` does not work on Windows

**To Reproduce**
1. Be on Windows
2. Run CMD/Powershell as admin
3. Be in a folder with `.\pw.bat`
4. Run `.\pw --init global`
5. Run `pxg --info`

**Expected behavior**
I want it not to fail because of wrong CMD syntax

**Screenshots**
![image](https://user-images.githubusercontent.com/104949/182168747-526b9aa5-2851-410e-9bc9-e85dfc824fe7.png)

**Desktop (please complete the following information):**
 - Python  version: N/A
 - OS: Windows

**Additional context**
None

**Comment by houbie** [comment]
I guess the script fails when your project is in a different drive then your home folder (D vs C).
Will try to reproduce...

**Comment by Darsstar** [comment]
I'll have a PR in a few min

**Comment by houbie** [comment]
Awesome, thanks for the contribution!
