### ISSUE TITLE
(🎁) Make projects "activatable" so that all tools are available

### ISSUE THREAD

**Issue by KotlinIsland** [pyprojectx/pyprojectx#23]
Having to go `px poetry install` is a little boilerplate-y, and configuring aliases for every Poetry(or whatever) subcommand is highly tedious.

Similar to how one activates a venv, what if you could do something like:
```
> px --activate
Activating project
(current-project) >
```

Then you can go
```
(current-project) > poetry install
```

**Comment by houbie** [comment]
with an alias and _px_ installed, you can just type `px i` (this is exactly what I do while developing)

**Comment by KotlinIsland** [comment]
@houbie I understand that `px i` is really useful and shorthand for `px poetry install`. But I still think it would be nice to be able to surface all tools (although, probably not aliases) to the top level.

**Comment by DetachHead** [comment]
this would be nice not just because it saves having to type two additional characters, but it will also improve compatibility with other tools that aren't aware of pyprojectx. some examples:

- https://github.com/pdm-project/tox-pdm/issues/54
- https://github.com/knowsuchagency/pdm-task-provider/issues/1

**Comment by houbie** [comment]
I could add an activate option that echoes the location of the activate script: `./pw -a main`
You could then activate it with `source $(./pw -a main)`
Not sure how this would work on windows though...

**Comment by DetachHead** [comment]
maybe there can be a consistent location in `.pyprojectx` that contains wrappers for each installed tool:
```
.pyprojectx/
├── scripts/
│   ├── pdm
│   └── pdm.bat
└── venvs/
    └── pdm-0ea4e8a18e16ec37852eafe4948fceb0-py3.12/
        ├── Lib/
        │   └── ...
        └── Scripts/
            ├── pdm
            └── pdm.exe
```

that way, you can easily make them available globally by adding `./.pyprojectx/scripts` to your `PATH`

**Comment by houbie** [comment]
Great idea, will look into it!

**Comment by houbie** [comment]
Final solution is different: instead of a single scripts dir, a dir per tool context is created.
This makes is possible to activate a tool context venv.
So if you install pdm as part of the main context, you can either run:

- `.pyprojectx/main/pdm --version`
- `source .pyprojectx/main/activate` + `pdm --version`

**Comment by DetachHead** [comment]
thanks for implementing this @houbie, a couple questions though:

- after updating to version 2.1.0, i don't see that `main` directory:
  ![image](https://github.com/pyprojectx/pyprojectx/assets/57028336/9bf3f46d-f6bc-4bf0-ab4b-3f5c056a0ea0)
  
  i see that new `pdm` directory with the `activate` script in it though, but does that mean each tool needs to have its own separate activation script? 
- running the activation script doesn't seem to work:
  ```
  > .\.pyprojectx\pdm\activate
  (.pyprojectx) PS C:\project> pdm --help
  pdm : The term 'pdm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is 
  correct and try again.
  At line:1 char:1
  + pdm --help
  + ~~~
      + CategoryInfo          : ObjectNotFound: (pdm:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
  ```

**Comment by houbie** [comment]
In 2.0.0 the philosophy changed from creating a separate virtual environment per tool, to group tools together in a _tool context_.
I typically create a main context with all build related tools (everything required in github actions):
`main= {requirements = ["pdm","ruff","pre-commit","px-utils"], post-install = "pre-commit install"}`
BTW: the _main_ context has special meaning; all its tools are available by default, f.e. `./pw pdm` will work without requiring an alias.

As of 2.1.0, a symlink to the scripts dir of each tool venv is created in _.pyprojectx_. This includes the standard venv activation script.
TBH, I only tested venv activation on Mac. Is it broken on windows when you run it via a symlink?

**Comment by DetachHead** [comment]
> Is it broken on windows when you run it via a symlink?

seems to be. unrelated to that issue though, i also use pyprojectx on a work PC where the admins have disabled symlinks. when attempting to use the new version on that PC, it crashes:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\project\.pyprojectx\pyprojectx\2.1.0-py3.12\Scripts\pyprojectx.exe\__main__.py", line 7, in <module>
  File "C:\project\.pyprojectx\pyprojectx\2.1.0-py3.12\Lib\site-packages\pyprojectx\cli.py", line 20, in main
    _run(sys.argv)
  File "C:\project\.pyprojectx\pyprojectx\2.1.0-py3.12\Lib\site-packages\pyprojectx\cli.py", line 59, in _run
    if _run_alias_cmds(config, cmd, pw_args, options):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\project\.pyprojectx\pyprojectx\2.1.0-py3.12\Lib\site-packages\pyprojectx\cli.py", line 77, in _run_alias_cmds
    _run_alias(
  File "C:\project\.pyprojectx\pyprojectx\2.1.0-py3.12\Lib\site-packages\pyprojectx\cli.py", line 130, in _run_alias
    _run_in_ctx(
  File "C:\project\.pyprojectx\pyprojectx\2.1.0-py3.12\Lib\site-packages\pyprojectx\cli.py", line 177, in _run_in_ctx
    venv = _ensure_ctx(config, ctx, env, options, pw_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\project\.pyprojectx\pyprojectx\2.1.0-py3.12\Lib\site-packages\pyprojectx\cli.py", line 193, in _ensure_ctx
    ctx_path.symlink_to(scripts_path, target_is_directory=True)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\pathlib.py", line 1387, in symlink_to
    os.symlink(target, self, target_is_directory)
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\project\\.pyprojectx\\venvs\\pdm-f938d443f677560d2786a15bf0f3e7d1-py3.12\\Scripts' -> 'C:\\project\\.pyprojectx\\pdm'
```

i'll raise separate issues for both of these
