### ISSUE TITLE
Running `./pw --install-px` through Git bash only install Windows script in `.pyprojectx` folder

### ISSUE THREAD

**Issue by g0di** [pyprojectx/pyprojectx#89]
When you install `px` utility through the `./pw --install-px` command line using a Git Bash terminal on a Windows machine you end up only with Windows scripts:

![image](https://github.com/pyprojectx/pyprojectx/assets/2545380/bd80ac1e-0478-46a7-9c0b-77eeef10c32a)

This is problematic then because I'm obviously not able to use `px` outside of Windows Terminal or Powershell:

![image](https://github.com/pyprojectx/pyprojectx/assets/2545380/25a53e47-1555-41e9-9212-7b57d7850f5d)

Considering that `.pyprojectx` folder has been properly added to my Path:

![image](https://github.com/pyprojectx/pyprojectx/assets/2545380/a112d4a3-825c-4ddf-8848-21016d41eab7)

I suggest that the command installing `px` and `pxg` utilities install both the Windows and Unix scripts (just as it happens when download `pw` itself)

> Note that I did not find any options in the CLI allowing to force installing UNIX scripts

> Using Pyprojectx `pw` `2.1.0` version

**Comment by houbie** [comment]
I released 2.1.1
All scripts are now being copied, but I didn't test it explicitly in windows.
Please let me know if it works as expected now.

**Comment by g0di** [comment]
This is working perfectly now, thank you very much for such a quick fix

![image](https://github.com/pyprojectx/pyprojectx/assets/2545380/eec385c2-3034-4f0b-baab-4d5754d314cf)
