### ISSUE TITLE
activate script seems to be broken on windows

### ISSUE THREAD

**Issue by DetachHead** [pyprojectx/pyprojectx#90]
**Describe the bug**
the `activate` script seems to be broken on windows.

**To Reproduce**
```
> .\.pyprojectx\pdm\activate
(.pyprojectx) PS C:\project> pdm --help
pdm : The term 'pdm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is 
correct and try again.
At line:1 char:1
+ pdm --help
+ ~~~
    + CategoryInfo          : ObjectNotFound: (pdm:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Expected behavior**
`pdm` command works since its context is activated

**Desktop (please complete the following information):**
 - Python  version: 3.12
 - OS: windows 10

**Additional context**
original discussion: https://github.com/pyprojectx/pyprojectx/issues/23#issuecomment-1979797136

**Comment by DetachHead** [comment]
@houbie this seems to still be broken in the latest version:

```
> .\.pyprojectx\pdm\activate
(.pyprojectx) PS C:\project> pdm --help
pdm : The term 'pdm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is   
correct and try again.
At line:1 char:1
+ pdm --help
+ ~~~
    + CategoryInfo          : ObjectNotFound: (pdm:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
(.pyprojectx) PS C:\project> .\pw --version
2.1.2
```

it still seems to be creating symlinks on windows too:
![image](https://github.com/pyprojectx/pyprojectx/assets/57028336/ec993ba6-5f70-4e8d-acfc-ff4c746804e9)

**Comment by houbie** [comment]
Weird 🤔 
This is what happens:
```
            if sys.platform.startswith("win"):
                shutil.rmtree(ctx_path, ignore_errors=True)
                ctx_path.mkdir(exist_ok=True)
                for file in scripts_dir.iterdir():
                    shutil.copy2(file, ctx_path)
```
What is the output of `python -c 'import sys; print(sys.platform)'` on your machine?

**Comment by houbie** [comment]
Are you running cygwin?
Would be better if I can check if symlinks are supported.

**Comment by houbie** [comment]
Can you check if it is fixed in 2.1.4?

**Comment by DetachHead** [comment]
> What is the output of `python -c 'import sys; print(sys.platform)'` on your machine?
```
> python -c 'import sys; print(sys.platform)'
win32
```
> Are you running cygwin?

nope, just powershell

>  Would be better if I can check if symlinks are supported.

tested on two machines, one with and without symlink support.

> Can you check if it is fixed in 2.1.4?

now it seems to be copying the folder on both machines, regardless of whether symlinks are enabled. the activate script still does not seem to work though (same error as before)

**Comment by houbie** [comment]
Seems to work only in cmd, not in powershell 🙁

**Comment by houbie** [comment]
Just released 2.1.5
Works on my machine now with powershell, hopefully on yours too 😉

**Comment by DetachHead** [comment]
looks like it's working now on my no-symlinks machine. but on my other machine that does support symlinks, it seems to hang for a few minutes before throwing this error:

```
> .\.pyprojectx\pdm\activate.ps1
The script failed due to call depth overflow.
    + CategoryInfo          : InvalidOperation: (0:Int32) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CallDepthOverflow
```

**Comment by houbie** [comment]
Oops 😊
My wrong, the ps script only gets fixed when symlinks are not supported

**Comment by houbie** [comment]
Yet another try to fix this for windows with/without symlink support.
Please reopen if you still face issues and  🙏 for the patience

**Comment by DetachHead** [comment]
working now on both machines. thanks!
