### ISSUE TITLE
(🎁) Use `uv`

### ISSUE THREAD

**Issue by KotlinIsland** [pyprojectx/pyprojectx#95]
Uv is really good, maybe it could be leveraged?

https://github.com/astral-sh/uv

**Comment by houbie** [comment]
`uv pip compile` now supports the `--universal` option, so it can help to generate a `pw.lock` file that is cross platform and cross python version

**Comment by houbie** [comment]
The release candidate is broken, reopening...

**Comment by houbie** [comment]
uv brings 🚀 speed compared with 🐌 pip 😃 
Waiting for https://github.com/astral-sh/uv/issues/4584 to be released before final release.
You can already give it a try by copying [pw 3.0.01rc2](https://github.com/pyprojectx/pyprojectx/blob/3.0.1rc2/pw) to your local project

**Comment by KotlinIsland** [comment]
@houbie https://github.com/astral-sh/uv/releases/tag/0.2.18 🚀

**Comment by KotlinIsland** [comment]
FYI: I have noticed that `uv` handles prereleases differently (needs `--prerelase=allow` to act similar to `pip`), causing my ci to need some refactors.

**Comment by houbie** [comment]
created #105
