### ISSUE TITLE
(🎁) fix locking of pyprojectx's own dependencies

### ISSUE THREAD

**Issue by KotlinIsland** [pyprojectx/pyprojectx#96]
Today my pipelines started failing because of a bad version of filelock being released (3.15.0). Because px does not lock its own dependencies, it just installed this latest version and failed when this was run: `.\pw --install-context pdm`

So what if px included its own dependencies in the lock file it generates:
```py
> px --lock
...
> cat pw.lock
[self]
requirements = [..., filelock="3.14.0", ...]
hash = "369465d3c365b066bab596c033706a36"

[pdm]
requirements = [...]
hash = "469465d3c365b066bab596c033706a35"
```

I guess that the wrapper would need logic to extract this information from the lock file.

**Comment by houbie** [comment]
Pyprojectx _should_ have its own dependencies locked. I'll look into it...

**Comment by houbie** [comment]
pyprojectx uses the [pdm-build-locked](https://pdm-build-locked.readthedocs.io/en/stable/index.html) plugin to lock its own dependencies. Unfortunately I missed a breaking change in the plugin, causing it to silently stop locking all dependencies.

The result is that pyprojextx versions between 2.0.3 and 2.1.9 fail in its main main reason of existence: a stable dev experience 🙁

Thanks for reporting the issue and apologies for breaking your builds.

**Comment by DetachHead** [comment]
> The result is that pyprojextx versions between 2.0.3 and 2.1.9 fail in its main main reason of existence: a stable dev experience 🙁

@houbie i just want to let you know that pyprojectx has significantly improved our dev experience. i cant put into words how frustrating it was to deal with other tools (like poetry) that expect to be installed globally and constantly screw up my python installation before i found out about pyprojectx. im shocked that this project isnt more well known.

i really appreciate how quickly you address the issues we've raised. you single handedly made python bearable for me and i hope pyprojectx gets the recognition it deserves
